name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main # Déclenche l'action sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy frontend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend/*"
          target: "/home/ubuntu/alina/"

      - name: Setup or restart frontend service
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Créer le service systemd si non existant
            sudo -su root

            cd /home/ubuntu/alina/frontend
            npm i
            npm run build
            rm -rf /var/www/alina-frontend/dist
            sudo mkdir -p /var/www/alina-frontend
            sudo cp -r dist /var/www/alina-frontend
